<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Products extends Seeder
{
    public function run()
    {
        $data = [
            [
                'name' => 'Sapiens: A Brief History of Humankind by Noah Harari',
                'description' => 'Buku ini mengupas sejarah manusia dari awal hingga saat ini, menggabungkan aspek biologi, sejarah, dan filsafat. Cocok untuk remaja dewasa yang ingin memahami asal-usul manusia dan bagaimana kita membentuk dunia saat ini.',
                'price' => 350000,
                'image' => 'product1.jpg',
                'stock' => rand(0, 100),
                'discount' => rand(0, 25),
                'sold' => rand(0, 10),
                'status' => 'active',
                'category_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Ready Player One by Ernest Cline',
                'description' => 'Petualangan seru di dunia virtual yang menggabungkan nostalgia budaya pop dengan teknologi futuristik. Buku ini akan membawa pembaca dalam perjalanan mencari harta karun sambil merenungkan dampak teknologi terhadap kehidupan manusia.',
                'price' => 150000,
                'image' => 'product2.jpg',
                'stock' => rand(0, 100),
                'discount' => rand(0, 25),
                'sold' => rand(0, 10),
                'status' => 'active',
                'category_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Algoritma by Brian Christian and Tom Griffiths',
                'description' => 'Buku ini menjelaskan bagaimana algoritma bekerja dan bagaimana algoritma membentuk kehidupan kita sehari-hari. Dengan gaya penulisan yang menarik, buku ini membantu pembaca memahami konsep-konsep kompleks dalam ilmu komputer dengan cara yang mudah dipahami.',
                'price' => 725000,
                'image' => 'product3.jpg',
                'stock' => rand(0, 100),
                'discount' => rand(0, 25),
                'sold' => rand(0, 10),
                'status' => 'active',
                'category_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'The Martian by Andy Weir',
                'description' => 'Kisah seorang astronot yang terdampar di Mars dan perjuangannya untuk bertahan hidup. Novel ini memadukan elemen sains fiksi dengan kisah survival yang menegangkan, serta menyoroti pentingnya kecerdasan dan kreativitas dalam menghadapi situasi sulit.',
                'price' => 135000,
                'image' => 'product4.jpg',
                'stock' => rand(0, 100),
                'discount' => rand(0, 25),
                'sold' => rand(0, 10),
                'status' => 'active',
                'category_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'The Three-Body Problem by Liu Cixin',
                'description' => 'Novel fiksi ilmiah yang berasal dari Tiongkok ini menceritakan tentang kontak pertama antara manusia dan peradaban alien. Buku ini menawarkan pandangan yang unik tentang peradaban manusia dan tempat kita di alam semesta.',
                'price' => 600000,
                'image' => 'product5.jpg',
                'stock' => rand(0, 100),
                'discount' => rand(0, 25),
                'sold' => rand(0, 10),
                'status' => 'active',
                'category_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'The Godfather by Mario Puzo',
                'description' => 'Novel klasik yang diadaptasi menjadi film terkenal ini mengisahkan keluarga mafia Corleone dan perjuangan mereka untuk mempertahankan kekuasaan. Buku ini menawarkan pandangan yang dalam tentang kekuasaan, keluarga, dan moralitas.',
                'price' => 250000,
                'image' => 'product6.jpg',
                'stock' => rand(0, 100),
                'discount' => rand(0, 25),
                'sold' => rand(0, 10),
                'status' => 'active',
                'category_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'The Power of Habit: Why We Do What We Do in Life and Business ',
                'description' => 'Dalam The Power of Habit, reporter bisnis pemenang penghargaan Charles Duhigg membawa kita ke tepi penemuan ilmiah yang menjelaskan mengapa kebiasaan ada dan bagaimana mereka dapat diubah. Dengan menyaring sejumlah besar informasi menjadi narasi yang menarik yang membawa kita dari ruang rapat Procter & Gamble ke pinggir lapangan NFL hingga garis depan gerakan hak-hak sipil, Duhigg menyajikan pemahaman baru tentang sifat manusia dan potensinya. Inti dari The Power of Habit adalah argumen yang menggembirakan: Kunci untuk berolahraga secara teratur, menurunkan berat badan, menjadi lebih produktif, dan mencapai kesuksesan adalah memahami bagaimana kebiasaan bekerja. Seperti yang ditunjukkan Duhigg, dengan memanfaatkan ilmu baru ini, kita dapat mengubah bisnis, komunitas, dan kehidupan kita.',
                'price' => 165000,
                'image' => 'product7.jpg',
                'stock' => rand(0, 100),
                'discount' => rand(0, 25),
                'sold' => rand(0, 10),
                'status' => 'active',
                'category_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'The Concept Of AI Ethics And Innovation Profiling by Indra Gamayanto',
                'description' => 'Inovasi adalah tantangan terbesar dan terpenting di era perkembangan teknologi informasi yang sangat pesat. Oleh karena itu, kami menciptakan konsep profil inovasi untuk menjawab perkembangan ini.',
                'price' => 550000,
                'image' => 'product8.jpg',
                'stock' => rand(0, 100),
                'discount' => rand(0, 25),
                'sold' => rand(0, 10),
                'status' => 'active',
                'category_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Social Media Profiling by Indra Gamayanto',
                'description' => 'Media sosial adalah gaya hidup yang tidak bisa dipisahkan dari kita. Dalam buku ini, kami akan menjelaskan konsep profil mood-berpikir-logika, tujuh lapisan hoax, profil anti-hoax, profil anti-cyberbullying, profil influencer, kecerdasan kepemimpinan 1.0 & 2.0, dan profil privasi. Semua ini adalah hal-hal yang terkait dengan media sosial.',
                'price' => 550000,
                'image' => 'product9.jpg',
                'stock' => rand(0, 100),
                'discount' => rand(0, 25),
                'sold' => rand(0, 10),
                'status' => 'active',
                'category_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Harry Potter Box Set: The Complete Collection',
                'description' => 'Harry Potter Box Set: Koleksi Lengkap oleh J.K. Rowling. Semua tujuh eBook dalam seri Harry Potter yang memenangkan banyak penghargaan dan terjual secara internasional, tersedia dalam satu unduhan dengan seni sampul yang menakjubkan oleh Olly Moss. Nikmati cerita-cerita yang telah menangkap imajinasi jutaan orang di seluruh dunia.',
                'price' => 1500000,
                'image' => 'product10.jpg',
                'stock' => rand(0, 100),
                'discount' => rand(0, 25),
                'sold' => rand(0, 10),
                'status' => 'active',
                'category_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
            ],
        ];
        $this->db->table('products')->insertBatch($data);
    }
}
